server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*log

  - job_name: user-logging
    static_configs:
      - targets:
          - localhost
        labels:
          job: user_loging
          __path__: /datadrive/docker/containers/*/*.log

    pipeline_stages:

      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            log: log

#       --log-opt tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
      - regex:
          expression: (?P<image_name>((.*\/)?(?P<name>[^|]*[^|]))).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: "tag"


      - labels:

          image_name: image_name
          container_name: container_name
          image_id: image_id
          container_id: container_id


      - output:
          source: log