auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

#limits_config:
#  ingestion_rate_mb: 200
#  max_query_length: 2000h
#  max_query_parallelism: 64
#  max_query_series: 2000
#  cardinality_limit: 200000
#  max_concurrent_tail_requests: 30
#  retention_period: 2000h
#  split_queries_by_interval: 24h
#  max_streams_per_user: 100000

frontend:
  max_outstanding_per_tenant: 4096
  compress_responses: true

#ruler:
#  alertmanager_url: http://alertmanager:9093
