version: "3"

services:
  docs:
    image: techdocs
    build: .
    volumes:
      - ./build/html:/usr/share/nginx/html
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.technical-docs.loadbalancer.server.port=80
      - traefik.http.routers.technical-docs.rule=Host(`localhost`) && PathPrefix(`/techdocs`)
      - traefik.http.routers.technical-docs.middlewares=technical-docs-stripprefix
      - traefik.http.middlewares.technical-docs-stripprefix.stripprefix.prefixes=/techdocs
  
networks:
  traefik-public:
    external: true