name: Generate documentation and deploy to Pages
on:
  push:
    branches:
      - "master"
    ## run if changes in docs directory
    paths:
      - docs/**
      - .github/workflows/build-and-deploy-documentation.yml
  
jobs:
  build-and-deploy:
    # Ensures that only one deploy task per branch/environment will run at a time.
    concurrency:
      group: environment-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          cd docs && pip3 install -r requirements.txt && make generate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs/build

      - name: Install and Build translations
        run: |
          cd docs
          sphinx-build -b gettext . build/gettext
          sphinx-intl update -p build/gettext -l it -l es -l lv

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto changes
          
      - name: Deploy Dev SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            git clone https://github.com/interlink-project/interlink-project.git /datadrive/data/interlink-project || (cd /datadrive/data/interlink-project && git pull --ff-only)
            cd /datadrive/data/interlink-project/docs/source
            export BASE_URL=/en
            sphinx-build -b html -D language=es . ../build/html/es
            export BASE_URL=/es
            sphinx-build -b html -D language=en . ../build/html/en
            export BASE_URL=/it
            sphinx-build -b html -D language=it . ../build/html/it
            export BASE_URL=/lv
            sphinx-build -b html -D language=lv . ../build/html/lv
            
            cd /datadrive/data/interlink-project/docs
            docker-compose up -d
