name: Generate documentation and deploy to Pages
on:
  push:
    branches:
      - "master"
    ## run if changes in docs directory
    # paths:
    #   - docs/**
  
jobs:
  build-and-deploy:
    # Ensures that only one deploy task per branch/environment will run at a time.
    concurrency:
      group: environment-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          cd docs && pip3 install -r requirements.txt && make generate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs/build/html