name: update-zgz-environment
on:
  repository_dispatch:
    types: [update-zgz-environment]

  release:
    tags: zgz**

  workflow_dispatch:

jobs:
  deploy:
    # Ensures that only one deploy task per branch/environment will run at a time.
    concurrency:
      group: environment-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev SSH
        uses: appleboy/ssh-action@master
        env:
          LOOMIO_AAC_APP_SECRET: ${{ secrets.ZGZ_LOOMIO_AAC_APP_SECRET }}
          LOOMIO_SECRET_COOKIE_TOKEN: ${{ secrets.ZGZ_LOOMIO_SECRET_COOKIE_TOKEN }}
          LOOMIO_SMTP_USERNAME: ${{ secrets.ZGZ_LOOMIO_SMTP_USERNAME }}
          LOOMIO_SMTP_PASSWORD: ${{ secrets.ZGZ_LOOMIO_SMTP_PASSWORD }}
          LOOMIO_DEVISE_SECRET: ${{ secrets.ZGZ_LOOMIO_DEVISE_SECRET }}
        with:
          host: ${{ secrets.ZGZ_HOST }}
          username: ${{ secrets.ZGZ_USERNAME }}
          key: ${{ secrets.ZGZ_SSH_KEY }}
          envs: LOOMIO_AAC_APP_SECRET,LOOMIO_SECRET_COOKIE_TOKEN,LOOMIO_SMTP_USERNAME,LOOMIO_SMTP_PASSWORD,LOOMIO_DEVISE_SECRET
          script: |
            export LOOMIO_SMTP_USERNAME=${{ secrets.ZGZ_LOOMIO_SMTP_USERNAME }}
            export LOOMIO_AAC_APP_SECRET=${{ secrets.ZGZ_LOOMIO_AAC_APP_SECRET }}
            export MAIL_PASSWORD=${{ secrets.ZGZ_MAIL_PASSWORD }}
            export LOOMIO_SECRET_COOKIE_TOKEN=${{ secrets.ZGZ_LOOMIO_SECRET_COOKIE_TOKEN }}
            export LOOMIO_SMTP_PASSWORD=${{ secrets.ZGZ_LOOMIO_SMTP_PASSWORD }}        
            export LOOMIO_DEVISE_SECRET=${{ secrets.ZGZ_LOOMIO_DEVISE_SECRET }}
            export GRAFANA_USERNAME=${{ secrets.ZGZ_GRAFANA_USERNAME }}
            export GRAFANA_PASSWORD=${{ secrets.ZGZ_GRAFANA_PASSWORD }}
            export ENVIRONMENT=zgz
            cd /datadrive/data/
            git clone https://github.com/interlink-project/interlink-project.git
            git pull --ff-only
            cd envs/development
            docker-compose --env-file .env.zgz down --remove-orphans
            docker-compose --env-file .env.zgz pull
            docker network create traefik-public
            docker-compose --env-file .env.zgz up -d
            sleep 10
            docker-compose exec -T catalogue python /app/app/pre_start.py
            docker-compose exec -T catalogue ./seed.sh
            docker-compose exec -T coproduction python /app/app/pre_start.py
            docker-compose exec -T coproduction ./seed.sh
