name: update-zgz-environment
on:

  workflow_dispatch:

jobs:
  deploy:
    # Ensures that only one deploy task per branch/environment will run at a time.
#    concurrency:
#      group: environment-${{ github.ref }}
#      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PILOT-ZGZ SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ZGZ_HOST }}
          username: ${{ secrets.ZGZ_USERNAME }}
          key: ${{ secrets.ZGZ_SSH_KEY }}
          script: |
            export LOOMIO_SMTP_USERNAME=${{ secrets.ZGZ_LOOMIO_SMTP_USERNAME }}
            export LOOMIO_AAC_APP_SECRET=${{ secrets.ZGZ_LOOMIO_AAC_APP_SECRET }}
            export MAIL_PASSWORD=${{ secrets.ZGZ_MAIL_PASSWORD }}
            export LOOMIO_SECRET_COOKIE_TOKEN=${{ secrets.ZGZ_LOOMIO_SECRET_COOKIE_TOKEN }}
            export LOOMIO_SMTP_PASSWORD=${{ secrets.ZGZ_LOOMIO_SMTP_PASSWORD }}        
            export LOOMIO_DEVISE_SECRET=${{ secrets.ZGZ_LOOMIO_DEVISE_SECRET }}
            export GRAFANA_USERNAME=${{ secrets.ZGZ_GRAFANA_USERNAME }}
            export GRAFANA_PASSWORD=${{ secrets.ZGZ_GRAFANA_PASSWORD }}
            export ENVIRONMENT=zgz
            export ENVIRONMENTPATH=pilot-zgz/.env.zgz
            cd /datadrive/data/
            git clone https://github.com/interlink-project/interlink-project.git || (cd /datadrive/data/interlink-project && git pull --ff-only origin ${{ github.ref_name }})
            cd /datadrive/data/interlink-project/envs
            git checkout ${{ github.ref }}
            docker-compose -f demo/docker-compose.yml -f pilot-zgz/docker-compose.zgz.yml --env-file pilot-zgz/.env.zgz down --remove-orphans
            docker-compose -f demo/docker-compose.yml -f pilot-zgz/docker-compose.zgz.yml --env-filepilot-zgz/.env.zgz pull
            docker network create traefik-public || true
            docker network create grafana-network || true
            docker-compose -f /datadrive/data/interlink-project/envs/demo/docker-compose.yml -f /datadrive/data/interlink-project/envs/pilot-zgz/docker-compose.zgz.yml --env-file /datadrive/data/interlink-project/envs/pilot-zgz/.env.zgz up -d
            sleep 10
            docker-compose exec -T catalogue python /app/app/pre_start.py
            docker-compose exec -T catalogue ./seed.sh