name: update-dev-environment
on:
  repository_dispatch:
    types: [update-dev-environment]
  push:
    branches:
      - "master"
    paths:
      - envs/base/**
      - envs/development/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev SSH
        uses: appleboy/ssh-action@master
        env:
          DEV_LOOMIO_AAC_APP_SECRET: ${{ secrets.DEV_LOOMIO_AAC_APP_SECRET }}
          DEV_LOOMIO_SECRET_COOKIE_TOKEN: ${{ secrets.DEV_LOOMIO_SECRET_COOKIE_TOKEN }}
          DEV_LOOMIO_SMTP_USERNAME: ${{ secrets.DEV_LOOMIO_SMTP_USERNAME }}
          DEV_LOOMIO_SMTP_PASSWORD: ${{ secrets.DEV_LOOMIO_SMTP_PASSWORD }}        
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: DEV_LOOMIO_AAC_APP_SECRET,DEV_LOOMIO_SECRET_COOKIE_TOKEN,DEV_LOOMIO_SMTP_USERNAME,DEV_LOOMIO_SMTP_PASSWORD
          script: |
            export DEV_LOOMIO_SMTP_USERNAME=${{ secrets.DEV_LOOMIO_SMTP_USERNAME }}
            echo "VAR DEV_LOOMIO_SMTP_USERNAME = $DEV_LOOMIO_SMTP_USERNAME"
            cd /datadrive/data/interlink-project
            git pull --ff-only
            cd envs/development
            docker-compose pull
            docker-compose up -d
            # docker-compose exec -T catalogue python /app/app/pre_start.py
            # docker-compose exec -T coproduction python /app/app/pre_start.py
            # docker-compose exec -T catalogue python /app/app/initial_data.py
            # docker-compose exec -T coproduction python /app/app/initial_data.py
