name: update-dev-environment
on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-dev-environment]

  release:
    types: [ published ]

  push:
    branches:
      - "master"      
    paths:
      - ".github/workflows/update-dev-environment.yml"
      - "envs/development/**"

jobs:
  deploy:
    # Ensures that only one deploy task per branch/environment will run at a time.
    concurrency:
      group: environment-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export LOOMIO_SMTP_USERNAME=${{ secrets.DEV_LOOMIO_SMTP_USERNAME }}
            export LOOMIO_AAC_APP_SECRET=${{ secrets.DEV_LOOMIO_AAC_APP_SECRET }}
            export MAIL_PASSWORD=${{ secrets.DEV_MAIL_PASSWORD }}
            export LOOMIO_SECRET_COOKIE_TOKEN=${{ secrets.DEV_LOOMIO_SECRET_COOKIE_TOKEN }}
            export LOOMIO_SMTP_PASSWORD=${{ secrets.DEV_LOOMIO_SMTP_PASSWORD }}        
            export LOOMIO_DEVISE_SECRET=${{ secrets.DEV_LOOMIO_DEVISE_SECRET }}
            export LOOMIO_DEVISE_SECRET=${{ secrets.DEV_LOOMIO_DEVISE_SECRET }}
            export GRAFANA_USERNAME=${{ secrets.DEV_GRAFANA_USERNAME }}
            export GRAFANA_PASSWORD=${{ secrets.DEV_GRAFANA_PASSWORD }}
            export GOOGLE_PROJECT_ID=${{ secrets.GOOGLE_PROJECT_ID }}
            export GOOGLE_PRIVATE_KEY_ID=${{ secrets.GOOGLE_PRIVATE_KEY_ID }}
            export GOOGLE_PRIVATE_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }}
            export GOOGLE_CLIENT_EMAIL=${{ secrets.GOOGLE_CLIENT_EMAIL }}
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export DREMIO_USERNAME=${{ secrets.DREMIO_USERNAME }}
            export DREMIO_PASSWORD=${{ secrets.DREMIO_PASSWORD }}
            export ENVIRONMENT=development
            git clone https://github.com/interlink-project/interlink-project.git /datadrive/data/interlink-project || true
            cd /datadrive/data/interlink-project/envs/development
            git fetch --force --all --tags
            git checkout origin/${{ github.ref_name }} || git checkout ${{ github.ref_name }}
            pip3 install python-dotenv && python3 setup-dremio.py
            docker-compose pull
            docker network create traefik-public || true
            docker network create grafana-network || true
            docker-compose up -d
            sleep 10

            docker-compose exec -T catalogue python /app/app/pre_start.py
            docker-compose exec -T coproduction python /app/app/pre_start.py

            # Apply last migrations (if they exist)
            docker-compose exec -T catalogue alembic upgrade head
            docker-compose exec -T coproduction alembic upgrade head
            
            # Seed the database (if objects already exist, initial_data.py script updates them)
            docker-compose exec -T catalogue ./seed.sh
            docker-compose exec -T coproduction ./seed.sh
            
            # Give permissions to postgres user to access the database
            docker-compose exec -T db psql -U postgres -c "CREATE ROLE viewer  with LOGIN ENCRYPTED PASSWORD 'viewer';" || true
            docker-compose exec -T db psql -U postgres -c "GRANT CONNECT ON DATABASE coproduction_production TO viewer;" 
            docker-compose exec -T db psql -U postgres -c "GRANT CONNECT ON DATABASE catalogue_production TO viewer;" 
            docker-compose exec -T db psql -U postgres -c "GRANT USAGE ON SCHEMA public TO viewer;" 
            docker-compose exec -T db psql -U postgres -d coproduction_production -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO viewer;" 
            docker-compose exec -T db psql -U postgres -d catalogue_production -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO viewer;" 
            docker-compose exec -T db psql -U postgres -c "ALTER ROLE viewer WITH LOGIN;"
            
            
