name: update-demo-environment
on:
  workflow_dispatch:

jobs:
  deploy:
    # Ensures that only one deploy task per branch/environment will run at a time.
    concurrency:
      group: environment-${{ github.ref }}-demo
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Deploy Demo SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEMO_HOST }}
          username: ${{ secrets.DEMO_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            git clone https://github.com/interlink-project/interlink-project.git ${{ secrets.PATH }}/interlink-project || true
            
            cd ${{ secrets.PATH }}/interlink-project/envs/demo
            git fetch --force --all --tags
            git checkout --force origin/${{ github.ref_name }} || git checkout --force ${{ github.ref_name }}
            
            git restore .env
            
            echo "${{ secrets.SECRETS }}" >> .env
            echo "${{ secrets.SECRETS }}" > secrets.env
            
            docker-compose pull
            docker network create traefik-public || true
            docker network create grafana-network || true
            docker-compose up -d
            sleep 10

            sudo apt install python3-pip -y
            pip3 install python-dotenv && python3 setup-dremio.py

            docker-compose exec -T catalogue python /app/app/pre_start.py
            docker-compose exec -T coproduction python /app/app/pre_start.py

            # Apply last migrations (if they exist)
            docker-compose exec -T catalogue alembic upgrade head
            docker-compose exec -T coproduction alembic upgrade head
            
            # Seed the database (if objects already exist, initial_data.py script updates them)
            docker-compose exec -T catalogue ./seed.sh
            docker-compose exec -T coproduction ./seed.sh
            